### ISSUE TITLE
User can save Pokemon to their Favorites List.

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/pokedata#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a Pokemon to their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The search result of a Pokemon will display the Pokemon's detail. The page will have a heart next to the Pokemon's name. The heart will either be empty or a red heart depending on if the Pokemon has been marked as a favorite yet.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/128638922-dec5358c-8c94-4ad0-bd94-4a1aa36d2cf9.png)
![image](https://user-images.githubusercontent.com/58172952/128638937-ea493e7c-11b9-4119-b6f7-9ec83a2ec03d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a button of a heart icon to the search result of a Pokemon.
- [x] Ensure heart looks good on both mobile & desktop.
- [x] Add eventListener to the heart button for true or false if saved.
- [x] If true, the heart is red.
- [x] If false, the heart is clear.
- [x] Set up localStorage to store on data.js for when a Pokemon is saved.
- [x] Setup an object in the data model to keep track of Pokemon and uniqueId that are saved.
- [x] Check if multiple Pokemon can be saved to localStorage.
- [x] Check to see if previously saved Pokemon shows a red heart when it is searched again.
- [x] When searching a pokemon, check thru data.js for if that pokemon has been saved to determine color of heart.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
