### ISSUE TITLE
User can view their Favorites List.

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/pokedata#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/150503283-042c5999-9945-4ba9-b702-80b562a49e22.png)

![image](https://user-images.githubusercontent.com/58172952/152510004-644a5e6d-bef4-468e-955f-4ff1aa23ff4e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create Favorites link for desktop.
- [x] Create a Favorites link for mobile.
- [x] If no Pokemon are favorited, show a message prompting to search and favorite a Pokemon.
- [x] Create a new data-view page on html to display favorites.
- [x] Create a slot for each favorite Pokemon.
- [x] Allow 1 column of favorites on mobile.
- [x] Make sure it looks good on desktop and mobile.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
