### ISSUE TITLE
User can remove Pokemon from Favorites List.

### ISSUE THREAD

**Issue by rocky-truong** [rocky-truong/pokedata#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/58172952/155219137-f9e4a899-e479-4c96-a5fb-7b00c16bc849.png)
![image](https://user-images.githubusercontent.com/58172952/155219406-bda45b47-b621-44ca-8e87-d687e98cd146.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add button feature to heart icons in favorites view.
- [x] Create a modal that displays Yes or No when the heart icon is clicked.
- [x] Ensure background is grayed out when modal is open.
- [x] Ensure modal and buttons look good on both mobile and desktop.
- [x] If no is clicked, modal is closed and no changes are made.
- [x] If yes is clicked, modal is closed and the Pokemon is no longer a favorite.
- [x] Ensure Pokemon previously favorited and unfavorited can still be a favorite afterwards.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
